### ISSUE TITLE
Add cookiecutter Instructions including LICENSE and SHA256 checklist

### ISSUE THREAD

**Issue by bobleesj** [Billingegroup/staged-recipes-cookiecutter#21]
@sbillinge Could you please review? Perhaps we use the following content and update GitLab since the current post on GitLab doesn't use cookiecutter to my knowledge (it instructs forking the recipe repo and modifying the `meta.yaml` file manually.

----

### Requirements

- Python >=3.11
- pip install cookiecutter

### Instructions

1. Clone the repo and cd into the directory `cd staged-recipes-cookiecutter`
2. Type `cookiecutter https://github.com/billingegroup/staged-recipes-cookiecutter`. It prompts questions to dynamically populate the `meta.yml` file.
3. Answer the following questions. Use the default values provided in parentheses if no specific value is required:
    1. github_org (diffpy):
    2. module_name (diffpy.my_project): diffpy.srreal
    3. repo_name (diffpy.srreal):
    4. version (1.0.0): 1.3.1
    5. Select source 1 - PyPi or 2 - GitHub: 1
       1. Choose 1. Conda package can be built using PyPI's `sdist` containing requirements files, src/tests, and `pyproject.toml`
    6. project_short_description (Python package for doing science.):
    7. project_full_description (This is a Python package for doing science.):
    8. license_file (LICENSE.rst):
    9.  recipe_maintainers (sbillinge,):
    10. build_requirements ():
        1.  copy `requirements/build.txt` from the project repo.
        2.  Empty for pure Python packages, otherwise compilers will be required.
    11. host_requirements (python >=3.10, setuptools, setuptools-git-versioning >=2.0, pip,):
        1.  copy `requirements/host.txt`
        2.  `setuptools-git-versioning` is used to dynamically populate the version from the latest's GitHub's release tag
    12. runtime_requirements (python >=3.10, numpy,):
        1.  copy `requirements/run.txt`
    13. testing_requirements (pip, pytest,):
        1.  copy `requirements/test.txt`

4. Now, `<package-nmae>/meta.yaml` is generated dynamically.

### Post cookiecutter checklist

- [ ] Double-check the license information in `meta.yaml` against the license files in the project repository. If you are unsure, please confirm with Prof. Billinge.

- [ ] Double-check the `sha256` value in `meta.yaml` against the value provided in PyPI. Visit `https://pypi.org/project/<package-name>/<version>/#files`and click `view_hases`. Ex) https://pypi.org/project/diffpy.structure/3.2.1/#files

- [ ] For pure python packages, the `build` section under the `requirements` will be empty. Remove that section. Ex) https://github.com/conda-forge/diffpy.utils-feedstock/blob/main/recipe/meta.yaml

**Comment by bobleesj** [comment]
One more - include an instruction for conda-forge pre-release.

**Comment by sbillinge** [comment]
the text above looks good to me.  I would have to follow it step by step and have it succeed to know for sure, but it is close enough that I suggest to copy it into gitlab wiki (you can overwrite what is there) and we can tweak it when it is followed by someone who is not @bobleesj and it works.

**Comment by bobleesj** [comment]
conda-forge release/pre-release Instructions added to Gitlab under `Doing group releases ...` 

Since the latest version will be on GitLab, I will modify there with new feedback sourced from volunteers/you.
